# Generated by Django 3.2.8 on 2021-10-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EN', 'engine parts'), ('BR', 'brakes'), ('SE', 'seat'), ('LI', 'lights'), ('UN', 'underglow'), ('SP', 'spoilers')], max_length=2),
        ),
    ]
