# Generated by Django 3.2.8 on 2021-10-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='order_id',
            field=models.CharField(default=131311213131, max_length=30),
            preserve_default=False,
        ),
    ]
