# Generated by Django 3.2.8 on 2021-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211026_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='amount',
            field=models.IntegerField(default=1685),
            preserve_default=False,
        ),
    ]
